// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNJzSu6uv7dcNE8RZME_JDPWZJMuOz35c',
    appId: '1:501221011037:web:1579557eadda9ec08367b4',
    messagingSenderId: '501221011037',
    projectId: 'design-driven-dev-note-app',
    authDomain: 'design-driven-dev-note-app.firebaseapp.com',
    storageBucket: 'design-driven-dev-note-app.appspot.com',
    measurementId: 'G-4G72W6SKQ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWD-iXiM-qcucb3CIa89J8dKqKDvTC33s',
    appId: '1:501221011037:android:9a2936c1daa121e78367b4',
    messagingSenderId: '501221011037',
    projectId: 'design-driven-dev-note-app',
    storageBucket: 'design-driven-dev-note-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAh4iePalPy8zgM4UYLQ-3Ao8Va00rsAzw',
    appId: '1:501221011037:ios:32be499b9e116f1c8367b4',
    messagingSenderId: '501221011037',
    projectId: 'design-driven-dev-note-app',
    storageBucket: 'design-driven-dev-note-app.appspot.com',
    androidClientId: '501221011037-q235lekkf6sbr70frhhe53rjtrugelsq.apps.googleusercontent.com',
    iosClientId: '501221011037-q8rmrsq6u5cqo1lqvjfm4t31jeqd0kss.apps.googleusercontent.com',
    iosBundleId: 'com.example.notepadFirebaseDdd',
  );
}
